# Generated by Django 4.2.7 on 2023-12-13 15:55

import apps.delivery.models.shipping
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_paymentmethod_remove_order_shipping_address_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('traking_number', models.CharField(db_index=True, default=apps.delivery.models.shipping.generate_traking_reference, max_length=12, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('processing_time', models.CharField(blank=True, max_length=10, null=True, validators=[apps.delivery.models.shipping.ProcessingTimeValidator])),
                ('address_required', models.BooleanField(default=False)),
                ('price', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{5}(?:-\\d{4})?$')])),
                ('country', models.CharField(max_length=255)),
                ('shipping', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='delivery.shipping')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='shipping',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.shippingmethod'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='shipping', to='sales.order'),
        ),
    ]
