# Generated by Django 4.2.7 on 2023-12-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_shippingmethod_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'ordering': ['-default', '-created_at']},
        ),
    ]
