# Generated by Django 4.2.7 on 2023-12-13 15:48

import apps.sales.models.payment
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('alias', models.CharField(db_index=True, editable=False, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, default=apps.sales.models.payment.generate_payment_reference, max_length=12, unique=True)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.paymentmethod')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='payment', to='sales.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
